repos:
-   repo: https://github.com/psf/black
    rev: 20.8b0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0  # Use the ref you want to point at
    hooks:
    -   id: check-ast # Python syntax check
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    # -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
